### ISSUE TITLE
compiled files naming

### ISSUE THREAD

**Issue by ptompalski** [bcgov/FAIBCompiler#9]
hello!
I am trying to understand the differences between:
- `faib_compiled_smeries_ht`
- `faib_compiled_smries`
- `faib_compiled_spcsmries`
- `faib_compiled_spcsmries_siteage`

All of these names exist in the code, but I couldn't find a clear explanation on what the differences between these are, and why would every compilation have a different record count.

I found "non_PSP_data_dictionary_20240125.xlsx" when accessing the data, but the differences between the compilations are not explained there either.

I'd appreciate your help!
P.

**Comment by YongLuo007** [comment]
Hi Piotr,

Thanks for your question. The items you mentioned are the table names for the summaries based on summary level and contents. Specifically, faib_compiled_smeries_ht is the table used for storing the tree height summaries at the plot level. faib_compiled_smries is used to store volume, basal area and density at plot level. faib_compiled_spcsumries used for volume, basal area and density at plot+species level. faib_compiled_spcsmries_siteage is used for storing the site index and age summaries at the species+plot level. The data dictionary stores the column names and descriptions.
Please let me know if you have any other questions.
Cheers,

Yong

**Comment by ptompalski** [comment]
thanks Yong, 
this helps a lot!
